### ISSUE TITLE
Provide an overlay for including the package and/or allow setting the nixpkgs system

### ISSUE THREAD

**Issue by terlar** [utdemir/nixdu#2]
If you want to included this in a nix flake for example, or if you build packages via a different machine, you would need to be able to inject system to `sources.nixpkgs { }`. See this for example: https://github.com/nmattia/niv/issues/95#issuecomment-572147656

Or provide an overlay that don't refer to any specific nixpkgs could be used instead.

**Comment by utdemir** [comment]
Thanks! I just merged a branch adding an `overlay.nix` file, that should allow this project to be used with arbitrary `pkgs`.

I haven't used flakes before, and I'll take a look once it is released.

Please let me know if this doesn't work for you.

**Comment by terlar** [comment]
That worked well, thank you for providing the overlay!
